def draw_school():
    print("school:")
    print("--------------------------------------")
    print("       |    |       |    |       |    |          ")
    print("       |    |       |    |       |    |          ")
    print("       |    |       |    |       |    |          ")
    print("       |    |       |    |       |    |          ")
    print("       |    |       |    |       |    |          ")
    print("       |    |       |    |       |    |          ")
    print("       |    |       |    |       |    |          ")
    print("       |    |_______|    |_______|    |          ")
    print("       |                              |          ")
    print("       |             ___              |          ")
    print("       |             |  |             |          ")
    return
